"""Auto-checker for Lab 01. Do not edit this file.

Run it with:  pytest labs/01-variables/
The import shim below lets `import variables` find variables.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from variables import greeting, to_int, add_one, describe


def test_greeting():
    assert greeting("Sam") == "Hello, Sam!"
    assert greeting("Alex") == "Hello, Alex!"


def test_to_int_converts_text_to_number():
    result = to_int("42")
    assert result == 42
    assert isinstance(result, int)


def test_add_one():
    assert add_one("7") == 8
    assert add_one("0") == 1
    assert add_one("99") == 100


def test_describe():
    assert describe("Sam", 9) == "Sam is 9 years old."
    assert describe("Alex", 30) == "Alex is 30 years old."
