"""Auto-checker for Lab 05. Do not edit this file.

Run it with:  pytest labs/05-loops/
The import shim below lets `import loops` find loops.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from loops import sum_to, count_vowels, factorial, first_multiple, countdown


def test_sum_to():
    assert sum_to(5) == 15
    assert sum_to(1) == 1
    assert sum_to(10) == 55
    assert sum_to(0) == 0


def test_count_vowels():
    assert count_vowels("hello") == 2
    assert count_vowels("AEIOU") == 5
    assert count_vowels("xyz") == 0
    assert count_vowels("") == 0
    assert count_vowels("Programming") == 3


def test_factorial():
    assert factorial(0) == 1
    assert factorial(1) == 1
    assert factorial(4) == 24
    assert factorial(5) == 120
    assert factorial(6) == 720


def test_first_multiple():
    assert first_multiple([4, 9, 6, 7], 3) == 9
    assert first_multiple([1, 2, 3, 4], 2) == 2
    assert first_multiple([1, 3, 5], 2) is None
    assert first_multiple([], 5) is None
    assert first_multiple([10, 20, 30], 10) == 10


def test_countdown():
    assert countdown(5) == [5, 4, 3, 2, 1]
    assert countdown(1) == [1]
    assert countdown(0) == []
    assert countdown(3) == [3, 2, 1]
