"""Auto-checker for Lab 16. Do not edit this file.

Run it with:  pytest labs/16-data-analysis/
The import shim below lets `import analysis` find analysis.py in this folder,
whether you run one lab or the whole suite.

The tests load sales.csv from this lab's own folder, so they are fully offline and
deterministic. Floats are compared with pytest.approx.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pytest

from analysis import (
    load_rows,
    total_sales,
    average_sale,
    sales_by_product,
    top_product,
)

HERE = Path(__file__).resolve().parent
CSV_PATH = HERE / "sales.csv"


def test_load_rows():
    rows = load_rows(CSV_PATH)
    assert len(rows) == 6
    assert rows[0] == {"product": "Widget", "amount": "30.00"}
    # values arrive as text from the CSV
    assert isinstance(rows[0]["amount"], str)


def test_total_sales():
    rows = load_rows(CSV_PATH)
    assert total_sales(rows) == pytest.approx(96.0)


def test_average_sale():
    rows = load_rows(CSV_PATH)
    assert average_sale(rows) == pytest.approx(16.0)


def test_sales_by_product():
    rows = load_rows(CSV_PATH)
    totals = sales_by_product(rows)
    assert totals["Widget"] == pytest.approx(50.0)
    assert totals["Gadget"] == pytest.approx(30.0)
    assert totals["Gizmo"] == pytest.approx(16.0)
    assert set(totals) == {"Widget", "Gadget", "Gizmo"}


def test_top_product():
    rows = load_rows(CSV_PATH)
    assert top_product(rows) == "Widget"
