"""Auto-checker for Lab 02. Do not edit this file.

Run it with:  pytest labs/02-operators/
The import shim below lets `import operators` find operators.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from operators import (
    rectangle_area,
    is_even,
    average,
    can_vote,
    seconds_to_minutes,
)


def test_rectangle_area():
    assert rectangle_area(3, 4) == 12
    assert rectangle_area(5, 5) == 25
    assert rectangle_area(1, 0) == 0
    assert rectangle_area(2.5, 4) == 10.0


def test_is_even():
    assert is_even(2) is True
    assert is_even(0) is True
    assert is_even(3) is False
    assert is_even(7) is False
    assert is_even(-4) is True
    assert is_even(-3) is False


def test_average():
    assert average(3, 6, 9) == 6.0
    assert average(1, 2, 3) == 2.0
    assert average(0, 0, 0) == 0.0
    result = average(1, 1, 1)
    assert isinstance(result, float)


def test_can_vote():
    assert can_vote(18) is True
    assert can_vote(19) is True
    assert can_vote(65) is True
    assert can_vote(17) is False
    assert can_vote(0) is False


def test_seconds_to_minutes():
    assert seconds_to_minutes(130) == (2, 10)
    assert seconds_to_minutes(60) == (1, 0)
    assert seconds_to_minutes(0) == (0, 0)
    assert seconds_to_minutes(59) == (0, 59)
    assert seconds_to_minutes(3661) == (61, 1)
