"""Auto-checker for Lab 06. Do not edit this file.

Run it with:  pytest labs/06-lists-tuples/
The import shim below lets `import sequences` find sequences.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from sequences import largest, evens, reverse_list, second_item, total_and_count


def test_largest():
    assert largest([3, 7, 2]) == 7
    assert largest([10]) == 10
    assert largest([-5, -2, -9]) == -2


def test_largest_empty_is_none():
    assert largest([]) is None


def test_evens():
    assert evens([1, 2, 3, 4]) == [2, 4]
    assert evens([2, 4, 6]) == [2, 4, 6]
    assert evens([1, 3, 5]) == []
    assert evens([]) == []
    # order is preserved
    assert evens([10, 7, 4, 1, 6]) == [10, 4, 6]


def test_reverse_list_returns_new_reversed():
    assert reverse_list([1, 2, 3]) == [3, 2, 1]
    assert reverse_list(["a", "b"]) == ["b", "a"]
    assert reverse_list([]) == []


def test_reverse_list_does_not_mutate_input():
    original = [1, 2, 3]
    reverse_list(original)
    assert original == [1, 2, 3]


def test_second_item():
    assert second_item([10, 20, 30]) == 20
    assert second_item(["a", "b", "c"]) == "b"


def test_total_and_count():
    assert total_and_count([1, 2, 3]) == (6, 3)
    assert total_and_count([10]) == (10, 1)
    assert total_and_count([]) == (0, 0)
