"""Auto-checker for Lab 15. Do not edit this file.

Run it with:  pytest labs/15-web-apis/
The import shim below lets `import webapi` find webapi.py in this folder,
whether you run one lab or the whole suite.

The tests load sample_posts.json from this lab's own folder, so they are fully offline
and deterministic. No network calls anywhere.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import json

from webapi import parse_titles, posts_by_user, count_by_user, build_query_url

HERE = Path(__file__).resolve().parent
POSTS = json.loads((HERE / "sample_posts.json").read_text())


def test_sample_data_shape():
    # Guard: the fixture is what the tests assume.
    assert len(POSTS) == 5
    assert {p["id"] for p in POSTS} == {1, 2, 3, 4, 5}


def test_parse_titles():
    titles = parse_titles(POSTS)
    assert titles == [
        "First steps with Python",
        "Reading files",
        "Loops save time",
        "What is an API",
        "JSON is friendly",
    ]


def test_posts_by_user():
    user1 = posts_by_user(POSTS, 1)
    assert [p["id"] for p in user1] == [1, 2, 3]
    user2 = posts_by_user(POSTS, 2)
    assert [p["id"] for p in user2] == [4, 5]
    assert posts_by_user(POSTS, 99) == []


def test_count_by_user():
    assert count_by_user(POSTS) == {1: 3, 2: 2}


def test_build_query_url_sorts_keys():
    url = build_query_url("https://example.com/posts", {"userId": 1, "limit": 5})
    assert url == "https://example.com/posts?limit=5&userId=1"
