"""Auto-checker for Lab 14. Do not edit this file.

Run it with:  pytest labs/14-automation/
The import shim below lets `import automation` find automation.py in this folder,
whether you run one lab or the whole suite.

Every test builds its own temporary folder with the `tmp_path` fixture, so your real
files are never touched. The tests are fully offline and deterministic.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from automation import find_files, organize_by_extension, bulk_rename


def _make_files(folder, names):
    """Create empty files with the given names inside folder."""
    for name in names:
        (folder / name).write_text("x")


def test_find_files_returns_sorted_matching_files(tmp_path):
    _make_files(tmp_path, ["report.txt", "notes.txt", "photo.jpg", "data.csv"])
    result = find_files(tmp_path, ".txt")
    names = [p.name for p in result]
    assert names == ["notes.txt", "report.txt"]
    assert all(isinstance(p, Path) for p in result)


def test_find_files_skips_subfolders(tmp_path):
    _make_files(tmp_path, ["a.txt"])
    (tmp_path / "a_subfolder.txt").mkdir()  # a directory ending in .txt must be skipped
    result = find_files(tmp_path, ".txt")
    names = [p.name for p in result]
    assert names == ["a.txt"]


def test_organize_by_extension_moves_files_and_counts(tmp_path):
    _make_files(tmp_path, ["report.txt", "notes.txt", "photo.jpg", "data.csv"])
    counts = organize_by_extension(tmp_path)
    assert counts == {"txt": 2, "jpg": 1, "csv": 1}
    assert (tmp_path / "txt" / "report.txt").is_file()
    assert (tmp_path / "txt" / "notes.txt").is_file()
    assert (tmp_path / "jpg" / "photo.jpg").is_file()
    assert (tmp_path / "csv" / "data.csv").is_file()
    # originals no longer at the top level
    assert not (tmp_path / "report.txt").exists()


def test_bulk_rename_numbers_files_in_sorted_order(tmp_path):
    _make_files(tmp_path, ["banana.txt", "apple.txt", "cherry.txt"])
    count = bulk_rename(tmp_path, "file")
    assert count == 3
    names = sorted(p.name for p in tmp_path.iterdir() if p.is_file())
    assert names == ["file_1.txt", "file_2.txt", "file_3.txt"]


def test_bulk_rename_keeps_each_extension(tmp_path):
    _make_files(tmp_path, ["apple.csv", "banana.jpg"])
    count = bulk_rename(tmp_path, "img")
    assert count == 2
    names = sorted(p.name for p in tmp_path.iterdir() if p.is_file())
    # apple.csv sorts before banana.jpg, so img_1 keeps .csv and img_2 keeps .jpg
    assert names == ["img_1.csv", "img_2.jpg"]
