"""Auto-checker for Lab 13. Do not edit this file.

Run it with:  pytest labs/13-oop/
The import shim below lets `import shapes` find shapes.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pytest

from shapes import Rectangle, BankAccount


def test_rectangle_area():
    assert Rectangle(4, 3).area() == 12
    assert Rectangle(5, 5).area() == 25


def test_rectangle_perimeter():
    assert Rectangle(4, 3).perimeter() == 14
    assert Rectangle(5, 5).perimeter() == 20


def test_bank_account_starts_at_zero():
    assert BankAccount().balance == 0


def test_bank_account_deposit():
    acct = BankAccount()
    acct.deposit(100)
    assert acct.balance == 100
    acct.deposit(50)
    assert acct.balance == 150


def test_bank_account_withdraw():
    acct = BankAccount(100)
    acct.withdraw(30)
    assert acct.balance == 70


def test_overdraw_raises_value_error():
    acct = BankAccount(50)
    with pytest.raises(ValueError):
        acct.withdraw(1000)
    # balance is unchanged after the failed withdrawal
    assert acct.balance == 50
