"""Auto-checker for Lab 17. Do not edit this file.

Run it with:  pytest labs/17-capstone/
The import shim below lets `import capstone` find capstone.py in this folder,
whether you run one lab or the whole suite.

The read tests load orders.json from this lab's own folder. The write test uses the
tmp_path fixture so it never touches your real files. Everything is offline and
deterministic; floats are compared with pytest.approx.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import csv

import pytest

from capstone import load_orders, total_by_category, summary, write_report

HERE = Path(__file__).resolve().parent
ORDERS_PATH = HERE / "orders.json"


def test_load_orders():
    orders = load_orders(ORDERS_PATH)
    assert len(orders) == 6
    assert orders[0] == {"id": 1, "category": "books", "amount": 12.99}
    # JSON keeps number types, so amount is a float
    assert isinstance(orders[0]["amount"], float)


def test_total_by_category():
    orders = load_orders(ORDERS_PATH)
    totals = total_by_category(orders)
    assert totals["books"] == pytest.approx(25.98)
    assert totals["toys"] == pytest.approx(40.0)
    assert totals["food"] == pytest.approx(11.75)
    assert set(totals) == {"books", "toys", "food"}


def test_summary():
    orders = load_orders(ORDERS_PATH)
    result = summary(orders)
    assert result["count"] == 6
    assert result["total"] == pytest.approx(77.73)
    assert result["categories"] == ["books", "food", "toys"]


def test_write_report(tmp_path):
    orders = load_orders(ORDERS_PATH)
    report_path = tmp_path / "report.csv"

    rows_written = write_report(report_path, orders)
    assert rows_written == 3
    assert report_path.is_file()

    with open(report_path, newline="") as f:
        rows = list(csv.reader(f))

    # header plus one row per category, categories sorted alphabetically
    assert rows[0] == ["category", "total"]
    assert [r[0] for r in rows[1:]] == ["books", "food", "toys"]
    assert float(rows[1][1]) == pytest.approx(25.98)
    assert float(rows[2][1]) == pytest.approx(11.75)
    assert float(rows[3][1]) == pytest.approx(40.0)
