"""Auto-checker for Lab 11. Do not edit this file.

Run it with:  pytest labs/11-modules/
The import shim below lets `import toolbox` find toolbox.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pytest

from toolbox import circle_area, mean, most_common, pick


def test_circle_area():
    assert circle_area(1) == pytest.approx(3.141592653589793)
    assert circle_area(2) == pytest.approx(12.566370614359172)
    assert circle_area(0) == pytest.approx(0.0)


def test_mean():
    assert mean([2, 4, 6]) == 4
    assert mean([10, 20]) == 15


def test_most_common():
    assert most_common(["yes", "no", "yes", "yes"]) == "yes"
    assert most_common([1, 1, 2, 3]) == 1


def test_pick_is_deterministic():
    # With a fixed seed the choice is always the same (confirmed by running it).
    assert pick(["rock", "paper", "scissors"], 7) == "paper"
    assert pick(["a", "b", "c", "d"], 0) == "d"
    # Same seed, same call -> same result every time.
    assert pick(["a", "b", "c", "d"], 0) == pick(["a", "b", "c", "d"], 0)
