"""Auto-checker for Lab 10. Do not edit this file.

Run it with:  pytest labs/10-files/
The import shim below lets `import files_lab` find files_lab.py in this folder,
whether you run one lab or the whole suite.

Every test uses pytest's `tmp_path` fixture, so nothing is written outside a
temporary directory.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from files_lab import write_lines, read_lines, count_lines, append_line


def test_write_lines_creates_file_with_newlines(tmp_path):
    p = tmp_path / "out.txt"
    write_lines(p, ["alpha", "beta", "gamma"])
    assert p.read_text() == "alpha\nbeta\ngamma\n"


def test_write_lines_overwrites(tmp_path):
    p = tmp_path / "out.txt"
    write_lines(p, ["old"])
    write_lines(p, ["new"])
    assert p.read_text() == "new\n"


def test_read_lines_strips_newlines(tmp_path):
    p = tmp_path / "in.txt"
    p.write_text("one\ntwo\nthree\n")
    assert read_lines(p) == ["one", "two", "three"]


def test_write_then_read_round_trip(tmp_path):
    p = tmp_path / "round.txt"
    write_lines(p, ["a", "b", "c"])
    assert read_lines(p) == ["a", "b", "c"]


def test_count_lines(tmp_path):
    p = tmp_path / "count.txt"
    p.write_text("l1\nl2\nl3\nl4\n")
    assert count_lines(p) == 4


def test_append_line_keeps_existing(tmp_path):
    p = tmp_path / "log.txt"
    write_lines(p, ["first", "second"])
    append_line(p, "third")
    assert read_lines(p) == ["first", "second", "third"]
    assert count_lines(p) == 3
