"""Auto-checker for Lab 08. Do not edit this file.

Run it with:  pytest labs/08-functions/
The import shim below lets `import functions` find functions.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from functions import greet, add_all, apply_discount, build_profile, repeat


def test_greet_default():
    assert greet("Sam") == "Hello, Sam!"


def test_greet_custom_greeting():
    assert greet("Sam", "Welcome") == "Welcome, Sam!"
    assert greet(name="Ada", greeting="Hi") == "Hi, Ada!"


def test_add_all():
    assert add_all(1, 2, 3) == 6
    assert add_all(10, 20) == 30
    assert add_all(5) == 5


def test_add_all_empty_is_zero():
    assert add_all() == 0


def test_apply_discount_default():
    result = apply_discount(100)
    assert result == 90.0
    assert isinstance(result, float)


def test_apply_discount_custom_percent():
    assert apply_discount(200, 50) == 100.0
    assert apply_discount(100, 0) == 100.0


def test_build_profile_name_only():
    assert build_profile("Sam") == {"name": "Sam"}


def test_build_profile_with_details():
    assert build_profile("Sam", age=9, city="Reno") == {
        "name": "Sam",
        "age": 9,
        "city": "Reno",
    }


def test_repeat_default():
    assert repeat("ab") == "abab"


def test_repeat_custom_times():
    assert repeat("x", 3) == "xxx"
    assert repeat("hi", 1) == "hi"
    assert repeat("hi", 0) == ""
