"""Auto-checker for Lab 07. Do not edit this file.

Run it with:  pytest labs/07-dicts-sets/
The import shim below lets `import mappings` find mappings.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mappings import word_count, get_or_default, unique_sorted, merge, count_unique


def test_word_count():
    assert word_count("the cat the dog") == {"the": 2, "cat": 1, "dog": 1}
    assert word_count("") == {}
    assert word_count("hi") == {"hi": 1}


def test_word_count_is_case_insensitive():
    assert word_count("The the THE") == {"the": 3}


def test_get_or_default_present():
    assert get_or_default({"a": 1}, "a", 0) == 1


def test_get_or_default_missing():
    assert get_or_default({"a": 1}, "b", 0) == 0
    assert get_or_default({}, "x", "none") == "none"


def test_unique_sorted():
    assert unique_sorted([3, 1, 2, 1, 3]) == [1, 2, 3]
    assert unique_sorted([]) == []
    assert unique_sorted(["b", "a", "a"]) == ["a", "b"]


def test_merge_combines():
    assert merge({"a": 1}, {"b": 2}) == {"a": 1, "b": 2}


def test_merge_d2_wins_on_conflict():
    assert merge({"a": 1, "b": 2}, {"b": 9}) == {"a": 1, "b": 9}


def test_merge_does_not_mutate_inputs():
    d1 = {"a": 1}
    d2 = {"b": 2}
    merge(d1, d2)
    assert d1 == {"a": 1}
    assert d2 == {"b": 2}


def test_count_unique():
    assert count_unique([1, 1, 2, 3, 3, 3]) == 3
    assert count_unique([]) == 0
    assert count_unique(["a", "a", "a"]) == 1
