"""Auto-checker for Lab 03. Do not edit this file.

Run it with:  pytest labs/03-strings/
The import shim below lets `import strings` find strings.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from strings import (
    shout,
    initials,
    last_char,
    count_letter,
    is_palindrome,
)


def test_shout():
    assert shout("hi") == "HI!"
    assert shout("hello") == "HELLO!"
    assert shout("Already LOUD") == "ALREADY LOUD!"
    assert shout("") == "!"


def test_initials():
    assert initials("ada lovelace") == "AL"
    assert initials("grace murray hopper") == "GMH"
    assert initials("Alex") == "A"
    assert initials("alan TURING") == "AT"


def test_last_char():
    assert last_char("hello") == "o"
    assert last_char("a") == "a"
    assert last_char("Python") == "n"


def test_count_letter():
    assert count_letter("banana", "a") == 3
    assert count_letter("banana", "n") == 2
    assert count_letter("hello", "z") == 0
    assert count_letter("mississippi", "s") == 4


def test_is_palindrome():
    assert is_palindrome("Level") is True
    assert is_palindrome("racecar") is True
    assert is_palindrome("hello") is False
    assert is_palindrome("Anna") is True
    assert is_palindrome("a") is True
