"""Auto-checker for Lab 12. Do not edit this file.

Run it with:  pytest labs/12-data-formats/
The import shim below lets `import dataio` find dataio.py in this folder,
whether you run one lab or the whole suite.

CSV tests use pytest's `tmp_path` fixture, so nothing is written outside a
temporary directory.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from dataio import to_json, from_json, write_csv, read_csv


def test_to_json_known_string():
    assert to_json({"a": 1}) == '{"a": 1}'
    assert to_json([1, 2, 3]) == "[1, 2, 3]"


def test_from_json_known_string():
    assert from_json('{"a": 1}') == {"a": 1}
    assert from_json("[1, 2, 3]") == [1, 2, 3]


def test_json_round_trip():
    data = {"name": "Sam", "age": 9, "pets": ["cat", "dog"]}
    assert from_json(to_json(data)) == data
    assert from_json(to_json([1, [2, 3], {"x": True}])) == [1, [2, 3], {"x": True}]


def test_write_csv_creates_expected_text(tmp_path):
    p = tmp_path / "people.csv"
    write_csv(p, ["name", "age"], [["Alex", 30], ["Sam", 9]])
    text = p.read_text()
    lines = text.splitlines()
    assert lines[0] == "name,age"
    assert lines[1] == "Alex,30"
    assert lines[2] == "Sam,9"


def test_read_csv_returns_dicts(tmp_path):
    p = tmp_path / "people.csv"
    write_csv(p, ["name", "age"], [["Alex", 30], ["Sam", 9]])
    rows = read_csv(p)
    assert rows == [
        {"name": "Alex", "age": "30"},
        {"name": "Sam", "age": "9"},
    ]


def test_csv_round_trip(tmp_path):
    p = tmp_path / "round.csv"
    write_csv(p, ["city", "code"], [["Austin", "ATX"], ["Boston", "BOS"]])
    rows = read_csv(p)
    assert rows[0]["city"] == "Austin"
    assert rows[1]["code"] == "BOS"
