"""Auto-checker for Lab 09. Do not edit this file.

Run it with:  pytest labs/09-errors/
The import shim below lets `import errors` find errors.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pytest

from errors import safe_int, divide, get_item, parse_or_default


def test_safe_int_valid():
    assert safe_int("42") == 42
    assert safe_int("0") == 0
    assert safe_int("-7") == -7


def test_safe_int_invalid_returns_none():
    assert safe_int("hello") is None
    assert safe_int("12.5") is None
    assert safe_int("") is None


def test_divide_normal():
    assert divide(10, 2) == 5.0
    assert divide(9, 3) == 3.0


def test_divide_by_zero_raises_value_error():
    with pytest.raises(ValueError):
        divide(10, 0)


def test_divide_by_zero_message():
    with pytest.raises(ValueError, match="cannot divide by zero"):
        divide(1, 0)


def test_get_item_in_range():
    assert get_item([10, 20, 30], 0) == 10
    assert get_item([10, 20, 30], 2) == 30


def test_get_item_out_of_range_returns_none():
    assert get_item([10, 20], 5) is None
    assert get_item([], 0) is None


def test_parse_or_default_valid():
    assert parse_or_default("42", 0) == 42
    assert parse_or_default("-3", 99) == -3


def test_parse_or_default_invalid_returns_default():
    assert parse_or_default("hello", 0) == 0
    assert parse_or_default("", -1) == -1
    assert parse_or_default("3.5", 100) == 100
