"""Auto-checker for Lab 04. Do not edit this file.

Run it with:  pytest labs/04-conditionals/
The import shim below lets `import conditionals` find conditionals.py in this folder,
whether you run one lab or the whole suite.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from conditionals import grade, sign, fizzbuzz, ticket_price


def test_grade():
    assert grade(95) == "A"
    assert grade(90) == "A"
    assert grade(85) == "B"
    assert grade(80) == "B"
    assert grade(72) == "C"
    assert grade(70) == "C"
    assert grade(65) == "D"
    assert grade(60) == "D"
    assert grade(59) == "F"
    assert grade(0) == "F"


def test_sign():
    assert sign(5) == "positive"
    assert sign(-3) == "negative"
    assert sign(0) == "zero"
    assert sign(0.1) == "positive"
    assert sign(-0.1) == "negative"


def test_fizzbuzz():
    assert fizzbuzz(15) == "FizzBuzz"
    assert fizzbuzz(30) == "FizzBuzz"
    assert fizzbuzz(3) == "Fizz"
    assert fizzbuzz(9) == "Fizz"
    assert fizzbuzz(5) == "Buzz"
    assert fizzbuzz(10) == "Buzz"
    assert fizzbuzz(7) == "7"
    assert fizzbuzz(1) == "1"


def test_ticket_price():
    assert ticket_price(5) == 5
    assert ticket_price(12) == 5
    assert ticket_price(13) == 10
    assert ticket_price(40) == 10
    assert ticket_price(64) == 10
    assert ticket_price(65) == 7
    assert ticket_price(80) == 7
